version: 0.2

phases:
  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - cd infra_c
      - npm ci
      - node scanClientsTable.js
      - npm i -g cdk
      - cdk bootstrap
      - cdk deploy -e krny-snp-application-stack/AthenaInfraStack krny-snp-application-stack/GlueInfraStack krny-snp-application-stack/ApiGatewayInfraStack
      - cdk deploy --all --require-approval=never
