version: 0.2

env:
  parameter-store:
    clientonboardingconfig: "clientonboardingconfig"

phases:
  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - echo $clientonboardingconfig
      - cd infra_c
      - npm ci
      - node scanClientsTable.js
      - echo $clientonboardingconfig
      - npm i -g cdk
      - cdk deploy --all --require-approval=never
