version: 0.2

env:
  parameter-store:
    clientonboardingconfig: "clientonboardingconfig"

phases:
  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - cd infra_c
      - npm ci
      - node scanClientsTable.js
      - npm i -g cdk
      - cdk bootstrap
      - cdk destroy krny-snp-ui-stack --force
      - cdk destroy --all --force
