version: 0.2

env:
  parameter-store:
    DOMAIN_NAME: "domainName"
    ENV_NAME: "envNameApp"
    CERTIFICATE_ARN: "certificateArn"

phases:
  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - cd infra_c
      - npm ci
      - node scanClientsTable.js
      - npm i -g cdk
      - cdk bootstrap
      - cdk deploy --all --require-approval=never --outputs-file ./stackexports.json
      - cat ./stackexports.json
      - node prepareDashboardsUpload.js
