version: 0.2

phases:
  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - cd infra_c
      - npm ci
      - node scanClientsTable.js
      - echo $CODEBUILD_BUILD_ARN
      - echo $AWS_REGION
      - npm i -g cdk
      - cdk bootstrap
      - cdk deploy --all --require-approval=never --outputs-file ./stackexports.json
      - cat ./stackexports.json
      - aws s3 cp ./stackexports.json s3://krny-spi-2117584757-alpha/
